/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

 // --------------------------------------
 // Edicion propia
#include <stdbool.h>
bool validar_token(char* token);
// --------------------------------------


#ifndef _SERVERINTERACT_H_RPCGEN
#define _SERVERINTERACT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct params_escribir {
	char *token;
	char *nombre_archivo;
	char *contenido;
};
typedef struct params_escribir params_escribir;

struct params_leer {
	char *token;
	char *nombre_archivo;
	int posicion;
};
typedef struct params_leer params_leer;

#define serverInteract 0x1
#define v1 1

#if defined(__STDC__) || defined(__cplusplus)
#define escribir 1
extern  int * escribir_1(params_escribir *, CLIENT *);
extern  int * escribir_1_svc(params_escribir *, struct svc_req *);
#define leer 2
extern  char ** leer_1(params_leer *, CLIENT *);
extern  char ** leer_1_svc(params_leer *, struct svc_req *);
extern int serverinteract_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define escribir 1
extern  int * escribir_1();
extern  int * escribir_1_svc();
#define leer 2
extern  char ** leer_1();
extern  char ** leer_1_svc();
extern int serverinteract_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_params_escribir (XDR *, params_escribir*);
extern  bool_t xdr_params_leer (XDR *, params_leer*);

#else /* K&R C */
extern bool_t xdr_params_escribir ();
extern bool_t xdr_params_leer ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVERINTERACT_H_RPCGEN */
