/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "serverInteract.h"

bool_t
xdr_params_escribir (XDR *xdrs, params_escribir *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token, 7))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nombre_archivo, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->contenido, 1024))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_params_leer (XDR *xdrs, params_leer *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token, 20))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nombre_archivo, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->posicion))
		 return FALSE;
	return TRUE;
}
