/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "serverInteract.h"


void
serverinteract_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	params_escribir  escribir_1_arg;
	char * *result_2;
	params_leer  leer_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, serverInteract, v1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	char buf_token[20];
	char buf_cont[1024];
	char buf_nombre_archivo[256];

	escribir_1_arg.token = buf_token;
	escribir_1_arg.contenido = buf_cont;
	escribir_1_arg.nombre_archivo = buf_nombre_archivo;

	strcpy(escribir_1_arg.token, "1234");
	strcpy(escribir_1_arg.contenido, "This is a test");
	strcpy(escribir_1_arg.nombre_archivo, "Test.txt");
	
	result_1 = escribir_1(&escribir_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("Resultado escribir: %d\n", *result_1);

	leer_1_arg.token = escribir_1_arg.token;
	leer_1_arg.posicion = 0;
	leer_1_arg.nombre_archivo = escribir_1_arg.nombre_archivo;

	result_2 = leer_1(&leer_1_arg, clnt);
	if (result_2 == (char**)NULL) {
		clnt_perror(clnt, "call failed");
	}
	else
		printf("Resultado leer\n: %s\n", *result_2);


	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	serverinteract_1 (host);
exit (0);
}
